name: Build SDL1.2

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: |
          ./configure
          make
          mkdir -p out
          cp build/.libs/libSDL*.so* out/

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: |
          cd VisualC
          msbuild SDL.sln /p:Configuration=Release
          mkdir ../out
          cp Release/SDL.dll ../out/
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: sdl-${{ matrix.os }}
          path: out/
