name: Build SDL1.2 Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          cd VisualC
          msbuild SDL.sln /p:Configuration=Release
          mkdir ../out
          cp Release/SDL.dll ../out/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: sdl-windows
          path: out/
